---
- hosts: solr
  become: true

  vars_file:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: restart solr
      service: name=solr state=restarted

  tasks:
    - name: install java
      apt: name=openjdk-8-jdk state=present
    - name: download solr
      get_url:
        url: "solr download url {{ solr_version }}"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
    - name: expand solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README"
    - name: Run Solr install script with command
      command: >
        {{ download_dir}}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir}}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr 
        -p 8983
        creates={{ solr_dir }}/bin/solr
    - name: ensure solr is started and enabled at boot
      service: name=solr state=started enabled=yes

    # - name: change config
    #   command: something to change config
    #   notify: restart solr
