---
- name: install Apache
  hosts: all
  become: true

  tasks:
    # - name: install Apache
    #   command: yum install --quiet -y httpd http-devel
      # - name: copy configuration files
      #   command: >
      #     cp httpd.conf /etc/httpd/conf/httpd.conf
      #   - command: >
      #     cp httpd.vhosts /etc/https/conf/httpd.vhosts.conf
      # - name: Start Apache and configure it to run at boot
      #   command: service httpd start
      #   - command: chkconfig httpd on

    - name: install Apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present
    - name: copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd.vhosts
          dest: /etc/https/conf/httpd.vhosts.conf
    - name: make sure Apache is started now and at boot
      service:
        name: httpd
        state: started
        enabled: true
