---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    vars/api_key.yml

  tasks:
    - name: Echo api key which was injected into the env.
      shell: echo $API_KEY
      environment:
        API_KEY: "{{ api_key }}"
      register: echo_result

    - name: Show the result.
      debug: var=echo_result.stdout
