---
- name: install Apache
  hosts: centos
  become: true

  handlers:
    - import_tasks: handlers/apache.yml

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_defaults.yml"
        - "vars/apache_{{ ansible_os_family }}.yml"

  tasks:
    - import_tasks: tasks/apache.yml

- import_playbook: app.yml
