---
- hosts: centos
  become: true

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Tell SELlinux about SSH's new port.
      seport:
        ports: 2849
        proto: tcp
        setype: ssh_port_t
        state: present
        validate: "sshd -T -f %s"

    - name: Make sure SSH is more secure.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 2849"
      notify: restart ssh

    - name: Add user john doe.
      user:
        name: johndoe

    - name: Add sudo group rights for deployment user
      lineeeinfile:
        dest: /etc/sudoers
        regexp: "johndoe"
        line: "johndoe ALL=(ALL) NOPASSWD: ALL"
        state: "present"
        validate: "visudo -cf %s"

    - name: Remove unused packages.
      package:
        name:
          - httpd
          - nano
          - mailutils
        state: absent

    - name: Edit file permissions.
      file:
        path: /etc/ssh/sshd_config
        mode: 0600


    - name: Make sure everything's up to date.
      yum:
        name: "*"
        state: latest

    - name: Setup auto updates
      yum:
        name: yum-cron
        state: present

    - name: Ensure auto updates are running
      service:
        name: yum-cron
        state: started
        enabled: true


    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Configure ports in firewall.
      firewalld:
        state: "{{ items.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: true
        permanent: true
      with_items:
        - {state: 'enabled', port: 2849/tcp}
        - {state: 'enabled', port: 123/udp}

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true
